spring:
  application:
    name: eurekaserver
  security:
    user:
      name: cursoms-eureka-server
      password: 123456

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
